### ISSUE TITLE
Add feature to auto generation of genicam parameters

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ioc-adaravis#42]
make a makePVI.py script so that we can use the full Genicam name rather than the shortened record name

@coretl @marcelldls could either of you elaborate on this please?

**Comment by coretl** [comment]
Genicam XML contains things like:
- Parameter name
- Parameter type
- Parameter description
- A group for it to appear in on the GUI

We currently only use the name (which we shorten) and the type for making the database. The other fields are used in `makeEdl.py` to make the screens. The current approach of using `pvi convert` to make pvi yaml only has access to what's in the database. If we made a `makePvi.py` that operated on the genicam XML then it could make much better pvi yaml with full names and GUI groups.

**Comment by gilesknap** [comment]
Thanks Tom. I think we have enough of a solution for the time being, would you agree?

**Comment by coretl** [comment]
This will do for now, but we can leave this open and come back to it another time

**Comment by gilesknap** [comment]
completed in #40

**Comment by coretl** [comment]
I don't think #40 did all of this, there was still the shortened name, which requires creating a `makePvi.py` file, then creating the GUI from that, rather than converting the DB files...

**Comment by huywork** [comment]
Hi @coretl , @gilesknap,
Could you point me to an example of what the pvi yaml file can look like?

**Comment by coretl** [comment]
https://github.com/epics-containers/ibek-support/blob/main/ADSimDetector/simDetector.pvi.device.yaml

Look at makeAdl.py to see example of extracting group locations

**Comment by coretl** [comment]
https://github.com/epics-containers/ioc-adaravis/blob/4843cb35ae5b36369c2163f3e8271045b1f53d7a/ioc/start.sh#L63-L88 is where the pvi convert is run
